# Generated by Django 4.0.6 on 2023-05-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_created=True)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Tipo_de_Documento', models.CharField(max_length=50)),
                ('Fecha_de_Nacimiento', models.CharField(max_length=50)),
                ('Fecha_de_Vinculacion_a_la_compañia', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('Salario', models.IntegerField()),
                ('Tiempo_de_Vinculacion_a_la_compañia', models.CharField(max_length=50)),
                ('Edad_actual_del_empleado', models.IntegerField()),
            ],
        ),
    ]
